modLoader="javafml" 
loaderVersion="[34,)"
license="All rights reserved"

[[mods]]
modId="mushroomcraft"
version="0.1"
displayName="Mushroom Craft 2"


[[dependencies.mushroomcraft]] 
    modId="forge" 
    mandatory=true 
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mushroomcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"